# Generated by Django 3.2.7 on 2021-09-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortly_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortlinkinfo',
            name='guest',
        ),
    ]
