# Generated by Django 3.2.7 on 2021-09-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortly_app', '0002_remove_shortlinkinfo_guest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortlinkinfo',
            old_name='last_datetime',
            new_name='last_update',
        ),
    ]
