# Generated by Django 3.2.7 on 2021-09-09 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_id', models.CharField(editable=False, max_length=6, unique=True)),
                ('url_target', models.URLField(max_length=250, unique=True)),
                ('click_count', models.PositiveSmallIntegerField(default=0)),
                ('guest', models.CharField(blank=True, max_length=32, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shortlies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Short_Url',
                'verbose_name_plural': 'Short_Urls',
            },
        ),
        migrations.CreateModel(
            name='ShortLinkInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.CharField(blank=True, max_length=32, null=True)),
                ('last_datetime', models.DateTimeField(auto_now=True)),
                ('click_count', models.PositiveSmallIntegerField(default=0)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to='shortly_app.shortlink')),
            ],
        ),
    ]
