# Generated by Django 3.2.7 on 2021-09-09 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortly_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortlink',
            old_name='url_id',
            new_name='short_url',
        ),
        migrations.RemoveField(
            model_name='shortlink',
            name='click_count',
        ),
    ]
